---
title: "Wonder oREV link"
output: html_document
date: "2023-02-25"
---

```{r setup, include=FALSE}
library(tidyverse)
library(ggpubr)
library(tidyboot)
library(brms)
library(ggthemes)
library(geomtextpath)
```

# new Data

```{r}

wonder_data <- read_csv("../data/wonder_data.csv")
orev_data <- read_csv("../data/orev_data.csv")

link_data <- wonder_data%>%
  group_by(age, subjID)%>%
  summarise(wonder = mean(score))%>%
  left_join(orev_data%>%
              group_by(subjID)%>%
              summarise(orev = mean(correct)))%>%
  filter(!is.na(orev))%>%
  mutate(age_group = substr(age, 1,1))%>%
  ungroup()%>%
  distinct(subjID, .keep_all = T)

sel_items <- readRDS("../saves/determine_size.rds")%>%
  filter(size == 75)%>%
  distinct(iter,items)%>%
  unnest()%>%
  group_by(items)%>%
  summarise(n = n())%>%
  arrange(-n)%>%
  head(75)%>%
  pull(items)

link_data_select <- wonder_data%>%
  filter(word %in% sel_items)%>%
  group_by(age, subjID)%>%
  summarise(wonder = mean(score))%>%
  left_join(orev_data%>%
              group_by(subjID)%>%
              summarise(orev = mean(correct)))%>%
  mutate(age_group = substr(age, 1,1))%>%
  filter(!is.na(orev))%>%
  ungroup()%>%
  distinct(subjID, .keep_all = T)


```

```{r}
wonder_data%>%
  summarise(n = n_distinct(subjID))

orev_data%>%
  summarise(n = n_distinct(subjID))
```


```{r}
ggplot(link_data, aes(x = wonder, y = orev, col = age_group))+
  geom_abline(intercept = 0, slope = 1, lty = 3, alpha = .5)+
  geom_point(pch = 19,stroke = F,  alpha = .5, size = 2)+
  stat_cor(inherit.aes = F, aes(x = wonder, y = orev))+
  #geom_smooth(method = "lm")+
  #facet_wrap(~age_group)+
  lims(x = c(0,1), y = c(0,1))+
  theme_bw()
```
```{r}
ppcor::pcor.test(link_data$wonder, link_data$orev, link_data$age)
```


```{r}
ggplot(link_data_select, aes(x = wonder, y = orev, col = age_group))+
  geom_abline(intercept = 0, slope = 1, lty = 3, alpha = .5)+
  geom_point(pch = 19,stroke = F,  alpha = .5, size = 2)+
  stat_cor(inherit.aes = F, aes(x = wonder, y = orev))+
  #geom_smooth(method = "lm", inherit.aes = F, aes(x = wonder, y = orev))+
  facet_wrap(~age_group)+
  lims(x = c(0,1), y = c(0,1))+
  theme_bw()
```

```{r}
ppcor::pcor.test(link_data_select$wonder, link_data_select$orev, link_data_select$age)
```

```{r}
m_won_orev <- wonder_data%>%
  group_by(subjID)%>%
  group_by(age, subjID)%>%
  summarise(sum  = sum(score),
            n = n())%>%
  left_join(orev_data%>%
              group_by(subjID)%>%
              summarise(orev = sum(correct)))%>%
  filter(!is.na(orev))%>%
  ungroup()%>%
  mutate(age = scale(age),
         orev = scale(orev))%>%
  filter(subjID != "tGCnD9nu")
  

m1 <- brm(sum |trials(n) ~ age + orev, family = binomial, data = m_won_orev, chains = 4, cores = 4)

m1
```


# old Data

```{r}
orev_d <- read_csv("../../vocab/data/clean_data.csv")%>%
  filter(targetWord %in% readRDS("../../vocab/saves/selected_items_rasch.rds"))%>%
  group_by(subjID)%>%
  summarise(orev = mean(correct))

wonder_d <- wonder_data%>%
  group_by(age, subjID)%>%
  summarise(wonder = mean(score))

wonder_d%>%
  left_join(orev_d)%>%
  filter(!is.na(orev))%>%
  ggplot(aes(x = wonder, y = orev))+
  geom_abline(intercept = 0, slope = 1, lty = 3, alpha = .5)+
  geom_point(pch = 1, alpha = .5)+
  stat_cor()+
  lims(x = c(0,1), y = c(0,1))+
  theme_bw()
```
```{r}
orev_wonder <- wonder_d%>%
  left_join(orev_d)%>%
  filter(!is.na(orev))%>%
  distinct(subjID, .keep_all = T)

ppcor::pcor.test(orev_wonder$wonder, orev_wonder$orev, orev_wonder$age)

```

```{r}
om_won_orev <- wonder_data%>%
  group_by(age, subjID)%>%
  summarise(sum  = sum(score),
            n = n())%>%
  left_join(orev_d)%>%
  filter(!is.na(orev))%>%
  ungroup()%>%
  mutate(age = scale(age),
         orev = scale(orev))
  

om1 <- brm(sum |trials(n) ~ age + orev, family = binomial, data = om_won_orev, chains = 4, cores = 4)
```


```{r}
orev_stab <- orev_data%>%group_by(subjID)%>%
  summarise(orev2 = mean(correct))%>%
  left_join(orev_d)%>%
  na.omit(orev)%>%
  left_join(wonder_data%>% mutate(age_group = substr(age, 1,1))%>%distinct(subjID, .keep_all = T)%>%select(subjID, age, age_group), by = "subjID")

ppcor::pcor.test(orev_stab$orev2, orev_stab$orev, orev_stab$age)

orev_stab%>%
  summarise(mean_t1 = mean(orev), 
            mean_t2 = mean(orev2))

orev_stab%>%
  ggplot(aes(x = orev2, y = orev))+
  geom_abline(intercept = 0, slope = 1, lty = 3, alpha = .5)+
  geom_jitter(pch = 19, alpha = .5, fill = "grey", height = 0.01, width = 0.01)+
  #facet_grid(~age_group)+
  stat_cor()+
  lims(x = c(0,1), y = c(0,1))+
  theme_bw()

orev_stab%>%
  mutate(col = ifelse(orev2 < orev, "de","in"))%>%
  pivot_longer(cols = c(orev, orev2), names_to = "measure", values_to = "orev_score")%>%
  ggplot(aes(x = measure, y = orev_score))+
  geom_point(pch = 1)+
  geom_line(aes(group = subjID, col = col),  alpha = .5)+
  scale_color_manual(values = c("firebrick", "grey"), guide = F)+
  theme_bw()
```


```{r}
library(tidybayes)

bind_rows(
m1 %>%
  gather_draws(b_age, b_orev)%>%
  mutate(Predictor = recode(.variable,
                        b_age = "Age",
                        b_orev = "oREV score"),
         Predictor = factor(Predictor, levels = c("Age","oREV score")),
         time = "Concurrent"),
om1 %>%
  gather_draws(b_age, b_orev)%>%
  mutate(Predictor = recode(.variable,
                        b_age = "Age",
                        b_orev = "oREV score"),
         Predictor = factor(Predictor, levels = c("Age","oREV score")),
         time = "1 year ago"))%>%
  ggplot(aes(y = time, x = .value, fill = Predictor)) +
  stat_halfeye(alpha = .7, .width = c(.95, .80)) +
    labs(x = "Model Estimate", y ="")+
  #guides(fill = F)+
  #ggtitle("DV: Reaction Time (25m)")+
  geom_vline(xintercept = 0, linetype = "dashed") +
  xlim(-0.1,0.4)+
  scale_fill_colorblind(name = "Predictor")+
  theme_bw()
```


```{r}
library(blavaan)

m_data <- orev_data%>%
  filter(targetWord %in% readRDS("../../vocab/saves/selected_items_rasch.rds"))%>%
  group_by(subjID)%>%
  mutate(orev_half = ifelse(trial %%2 == 0, "orev_even", "orev_odd"))%>%
  group_by(subjID, orev_half)%>%
  summarise(orev = mean(correct))%>%
  pivot_wider(names_from = "orev_half", values_from = "orev")%>%
  left_join(wonder_data%>%
  group_by(subjID)%>%
  mutate(wonder_half = ifelse(trial %%2 == 0, "wonder_even", "wonder_odd"))%>%
  group_by(subjID, wonder_half)%>%
  summarise(wonder = mean(score))%>%
  pivot_wider(names_from = "wonder_half", values_from = "wonder"))%>%
  na.omit()%>%
  ungroup()%>%
  mutate_if(is.numeric, scale)


model <- 'wonder  =~ wonder_odd + wonder_even
          orev  =~ orev_even + orev_odd
          lang  =~ wonder + orev'

fit <- bsem(model, data = m_data, bcontrol = list(cores = 3), target = "stan", n.chains = 3, burnin = 2000, sample = 2000, save.lvs = T)


summary(fit, standardized = T,rsquare = T)

blavInspect(fit, what = "lvmeans")%>%as_tibble()%>%bind_cols(m_data)


```



